/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package genioswing;

import java.util.Random;

/**
 *
 * @author johnny
 */
public class TelaGenio extends javax.swing.JFrame {

    /**
     * Creates new form TelaGenio
     */
    public TelaGenio() {
        initComponents();
        lblAcertou.setVisible(false);
        lblErro.setText(" ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblQuest = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textPalpite = new javax.swing.JTextField();
        btnClick = new javax.swing.JButton();
        lblAcertou = new javax.swing.JLabel();
        lblErro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mizeravi1.jpg"))); // NOI18N
        getContentPane().add(lblQuest, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Que numero entre 0 e 5 estou pensando?");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 7, 428, 68));
        getContentPane().add(textPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 140, -1));

        btnClick.setText("Responder");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });
        getContentPane().add(btnClick, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        lblAcertou.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mizeravi2.png"))); // NOI18N
        lblAcertou.setDisabledIcon(null);
        getContentPane().add(lblAcertou, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        lblErro.setFont(new java.awt.Font("Noto Sans", 0, 18)); // NOI18N
        lblErro.setText("Eu tinha pensado em tal numero");
        getContentPane().add(lblErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 310, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        
        int palpite = Integer.parseInt(textPalpite.getText());
        System.out.println("palpite = "+palpite);
        
        lblErro.setText(" ");
        
        Random gerador = new Random();
        
        int valor = gerador.nextInt(5);
        
        if(palpite == valor){
            lblAcertou.setVisible(true);
            lblQuest.setVisible(false);
        }else{
            lblErro.setText("Eu tinha pensado no "+valor);
            valor = gerador.nextInt(5);
        }
        
    }//GEN-LAST:event_btnClickActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClick;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAcertou;
    private javax.swing.JLabel lblErro;
    private javax.swing.JLabel lblQuest;
    private javax.swing.JTextField textPalpite;
    // End of variables declaration//GEN-END:variables
}
